chapter6
shikibum/cho_nyumon pull request #4
Opened 2019-01-15 13:15 UTC by shikibum

2019-01-15 14:19 UTC, y310 requested changes

2019-01-15 14:19 UTC, y310 commented on chapter6.rb
> +  puts "#{key} - #{value}円 "
円のあとに不要な空白があります

2019-01-15 14:19 UTC, y310 commented on chapter6.rb
> +menu.keys.to_a
`to_a`はつけなくて良いです

2019-01-15 14:23 UTC, shikibum commented
@y310 再レビューお願いします🙏

2019-01-16 13:33 UTC, y310 approved these changes
👍

2019-01-17 05:30 UTC, merged